version: 2.1

jobs:
  node_18:
    docker:
      - image: cimg/node:18.11
    steps:
      - checkout
      - run: npm i
      - run: npm test
  node_16:
    docker:
      - image: cimg/node:16.18
    steps:
      - checkout
      - run: npm i
      - run: npm test
  node_14:
    docker:
      - image: cimg/node:14.20
    steps:
      - checkout
      - run: npm i
      - run: npm test


workflows:
  matrix-tests:
    jobs:
      - node_18
      - node_16
      - node_14
